volumes:
  postgres-data:

services:
 backend:
  build:
   context: ./backend
   dockerfile: Dockerfile
  volumes:
   - ./backend:/usr/src/app:delegated
   - /usr/src/app/node_modules
  ports:
   - 3001:3001
  environment:
   - NODE_ENV=development
 frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    ports:
      - "3000:5173"
    environment:
      - NODE_ENV=development
 postgres:
  container_name: postgres
  restart: always
  image: postgres:17
  environment:
    POSTGRES_PASSWORD: admin
    POSTGRES_USER: admin
    POSTGRES_HOST: 127.0.0.1
    POSTGRES_PORT: 5432
  ports:
    - 5432:5432
  volumes:
    - postgres-data:/var/lib/postgresql/data

  